# Generated by Django 5.1.4 on 2025-03-05 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_feedback_email_feedback_name_inquiry_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="email",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="name",
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="email",
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="name",
        ),
    ]
